name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      # Test the Code
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    

      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build . -t geraldakenji/demo-app:${{ env.VERSION }} 
      
      # Push the Docker Image
      - name: Push Docker Image
        run: |
          docker push geraldakenji/demo-app:${{ env.VERSION }}

      # UPdate the K8s Manifest Files
      - name: Update K8s Manifests
        run: |
          cat deploy/deployment.yml
          sed -i "s|image: geraldakenji/demo-app:.*|image: geraldakenji/demo-app:${{ env.VERSION }}|g" deploy/deployment.yml
          cat deploy/deployment.yml

    #   # Update Github
    #   - name: Commit the changes
    #     run: |
    #       git config --global user.email "<>"
    #       git config --global user.name "GitHub Actions"
    #       git add deploy/deployment.yml
    #       git commit -m "Update deployment.yml with new image version - ${{ env.VERSION }}"
    #       git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/infosecsingh/GitHub-Actions-ArgoCD.git
    #       git push origin main